name: alakazam-repertoire-2.0.0
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - conda-forge::r-base=4.0.5
  - conda-forge::r-alakazam=1.0.2
  - conda-forge::r-shazam=1.0.2
  - conda-forge::r-kableextra=1.3.4
  - conda-forge::r-knitr=1.33
  - conda-forge::r-stringr=1.4.0
  - conda-forge::r-dplyr=1.0.6
  - conda-forge::r-data.table
  - conda-forge::r-igraph
  - conda-forge::r-gplots
  - conda-forge::r-circlize
  - conda-forge::r-upsetr
  - conda-forge::r-gtools
  - rstudio
