name: QMKMK
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - conda-forge::r-base=4.1.2
  - bioconda::r-alakazam=1.2.0
  - bioconda::r-shazam=1.1.0
  - conda-forge::r-kableextra=1.3.4
  - conda-forge::r-knitr=1.33
  - conda-forge::r-stringr=1.4.0
  - conda-forge::r-dplyr=1.0.6
  - conda-forge::r-optparse=1.7.1
  - rstudio
  - conda-forge::r-gplots
  - conda-forge::r-circlize
  - conda-forge::r-upsetr
  - conda-forge::r-gtools
  - conda-forge::r-data.table
  - conda-forge::r-igraph
